# Generated by Django 3.1.6 on 2021-02-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmtools', '0005_marketernode_node_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketernode',
            name='parent_cut',
        ),
        migrations.AddField(
            model_name='marketernode',
            name='sub_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='How much to sent up the tree', max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketernode',
            name='node_cut',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='How much does this node get', max_digits=5),
        ),
    ]
