# Generated by Django 3.2.2 on 2021-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmtools', '0010_dummytarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytarget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
